### ISSUE TITLE
libspeedhack.cpp:344:16: error: conflicting declaration of C function ‘int gettimeofday(timeval*, void*)’ on Linux 4.16.18

### ISSUE THREAD

**Issue by A-R-M** [evg-zhabotinsky/libspeedhack#11]
**Operating System:**
GalliumOS 3.1

**Kernel**:
`Linux 4.16.18-galliumos`

**Architecture:**
`x86-64`

**Commit:**
e9f22acac790509cea4be38642f16557416a97dd

Ran `make` in the project directory and received the following output:
```
mkdir -p lib
g++ -std=c++11 -Wall   -fPIC -shared libspeedhack.cpp -ldl -o lib/libspeedhack.so
libspeedhack.cpp: In function ‘int gettimeofday(timeval*, void*)’:
libspeedhack.cpp:344:16: error: conflicting declaration of C function ‘int gettimeofday(timeval*, void*)’
 extern "C" int gettimeofday(timeval *tv, void *tz)
                ^~~~~~~~~~~~
In file included from libspeedhack.cpp:3:0:
/usr/include/x86_64-linux-gnu/sys/time.h:68:12: note: previous declaration ‘int gettimeofday(timeval*, __timezone_ptr_t)’
 extern int gettimeofday (struct timeval *__restrict __tv,
            ^~~~~~~~~~~~
libspeedhack.cpp: In function ‘time_t time(time_t*)’:
libspeedhack.cpp:402:24: error: call of overloaded ‘gettimeofday(timeval*, NULL)’ is ambiguous
  gettimeofday(&tv, NULL);
                        ^
In file included from libspeedhack.cpp:3:0:
/usr/include/x86_64-linux-gnu/sys/time.h:68:12: note: candidate: int gettimeofday(timeval*, __timezone_ptr_t)
 extern int gettimeofday (struct timeval *__restrict __tv,
            ^~~~~~~~~~~~
libspeedhack.cpp:344:16: note: candidate: int gettimeofday(timeval*, void*)
 extern "C" int gettimeofday(timeval *tv, void *tz)
                ^~~~~~~~~~~~
Makefile:19: recipe for target 'lib/libspeedhack.so' failed
make: *** [lib/libspeedhack.so] Error 1
```

Looking at the closed issues, I found #2, which lead to commit 6c8fd9657b7c724b8860fd072dac4e0b254a1dab being merged. Unfortunately, that change seems to have broken compilation for older Linux kernels.

I changed line 146 from the current:
```cpp
static int (*gettimeofday_orig)(timeval *tv, void *tz);
```

back to the previous:
```cpp
static int (*gettimeofday_orig)(timeval *tv, struct timezone *tz);
```

and changed line 344 from the current:
```cpp
extern "C" int gettimeofday(timeval *tv, void *tz)
```

back to the previous:
```cpp
extern "C" int gettimeofday(timeval *tv, struct timezone *tz)
```

After making those changes, compilation is successful.

**Comment by evg-zhabotinsky** [comment]
Should compile regardless of that argument's type now, guessing it with template magic.

**Comment by A-R-M** [comment]
Can confirm, d71c1a524381ada7fb36f633a27daf7aca2d547d compiles on my Linux 4.16.18 machine! 👍
